<?php require_once './templates/header.phtml' ?>


<h1> NUESTROS PRODUCTOS:</h1>
<table>
    <thead>
        <th>NOMBRE</th>
        <th>APELLIDO</th>
        <th>EMAIL</th>
    </thead>
<?php
    foreach($list as $item):?>
    <tbody>
        <tr>
            <td><?= $item->nombre?></td>
            <td><?= $item->apellido?></td>
            <td><?= $item->email?></td>
            
        </tr>
       
    </tbody>
    
<?php endforeach?>
</table>
<?php require_once './templates/footer.phtml' ?>