<?php require_once './templates/header.phtml' ?>


<h1> NUESTROS PRODUCTOS:</h1>
<form  method="post" action="updateClient/<?=$id?>">
<label >Ingrese sus datos</label>
<input type="text" name="nombre" placeholder="Ingrese nuevo nombre">
<input type="text" name="apellido" placeholder="Ingrese nuevo apellido">
<input type="text" name="email" placeholder="Ingrese nuevo mail">
<button type="submit">Actualizar</button>
</form>
<table>
    <thead>
        <th>NOMBRE</th>
        <th>APELLIDO</th>
        <th>EMAIL</th>
    </thead>
<?php
    foreach($list as $item):?>
    <tbody>
        <tr>
            <td><?= $item->nombre?></td>
            <td><?= $item->apellido?></td>
            <td><?= $item->email?></td>
        </tr>
       
    </tbody>
    
<?php endforeach?>
</table>
<?php require_once './templates/footer.phtml' ?>