<?php require_once './templates/header.phtml' ?>


<h1> NUESTROS PRODUCTOS:</h1>

<table>
    <thead>
        <th>NOMBRE</th>
        <th>PRECIO</th>
    </thead>
<?php
    foreach($list as $item):?>
    <tbody>
        <tr>
            <td><?= $item->nombre?></td>
            <td><?= $item->precio?></td>
        </tr>
    </tbody>
    
<?php endforeach?>
</table>


<?php require_once './templates/footer.phtml' ?>