<?php require_once './templates/header.phtml' ?>
<form method="post" action="addProduct">
    <label for="h5">Ingrese su producto</label>
    <input name="nombre" type="text" placeholder="nombre">
    <input name="precio" type="number" placeholder="precio">
    <button type="submit">Enviar</button>

</form>



<h1> NUESTROS PRODUCTOS:</h1>

<table>
    <thead>
        <th>NOMBRE</th>
        <th>PRECIO</th>
    </thead>
<?php
    foreach($list as $item):?>
    <tbody>
        <tr>
            <td><?= $item->nombre?></td>
            <td><?= $item->precio?></td>
        </tr>
    </tbody>
    
<?php endforeach?>
</table>


<?php require_once './templates/footer.phtml' ?>